services:
    database:
        image: 'mysql:latest'
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: main
            MYSQL_USER: app
            MYSQL_PASSWORD: password
        ports:
            - '3306:3306'
        volumes:
            - db-data:/var/lib/mysql

    mailer:
        image: schickling/mailcatcher
        ports:
            - "1025:1025"
            - "1080:1080"

volumes:
    db-data:
